default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: test_5_smith_development

test:
  <<: *default
  database: test_5_smith_test

production:
  <<: *default
  database: test_5_smith_production